web/protected/modules/expediente/controllers/DocumentController.php
<?php

class DocumentController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $defaultAction = 'lista';

    /**
     * @return array action filters
     */
    public static $_permissionControl = array(
        'read' => 'Consulta de DocumentController',
        'write' => 'Creación y Modificación de DocumentController',
        'admin' => 'Administración Completa  de DocumentController',
        'label' => 'Módulo de DocumentController'
    );

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'userGroupsAccessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        // en este array colocar solo los action de consulta
        return array(
            array('allow',
                'actions' => array('lista', 'consulta', 'registro', 'edicion', 'eliminacion', 'busqueda','busquedaAvanzada'),
                'pbac' => array('admin'),
            ),
            array('allow',
                'actions' => array('lista', 'consulta', 'registro', 'edicion', 'busqueda','busquedaAvanzada'),
                'pbac' => array('write'),
            ),
            array('allow',
                'actions' => array('lista', 'consulta',),
                'pbac' => array('read'),
            ),
            // este array siempre va asì para delimitar el acceso a todos los usuarios que no tienen permisologia de read o write sobre el modulo
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Lists all models.
     */
    public function actionLista() {
        $model = new Document('search');
        $model->unsetAttributes();  // clear any default values
        if ($this->hasQuery('Document')) {
            $model->attributes = $this->getQuery('Document');
        }
        $dataProvider = $model->search();
        $this->render('admin', array(
            'model' => $model,
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionBusqueda() {
        $expediente = new Document();
        $cedula = $_REQUEST['cedula'];
        $cedula_encontrada='';
        if (isset($_POST['cedula'])) {
            $c = 0;
            $resultado = Document::model()->busquedaExpediente($cedula);
            $resultadoTexto = Document::model()->busquedaHiperTexto($cedula);
            $resultadoFoto = Document::model()->foto($cedula);

        }
        if ($resultadoTexto) {
            $this->render('ficha', array('resultado' => $resultado, 'resultadoTexto' => $resultadoTexto,'resultadoFoto'=>$resultadoFoto));
        } else {
            $this->render("//msgBox", array('class' => 'errorDialogBox', 'message' => 'Número de Cédula no Existe en el Sistema'));
        }
    }
       public function actionBusquedaAvanzada() {
        $expediente = new Document();
        if (isset($_POST['cedula'])) {
        $cedula = $_REQUEST['cedula'];
        $cedula_encontrada='';
            $c = 0;
            $resultado = Document::model()->busquedaExpediente($cedula);
            $resultadoTexto = Document::model()->busquedaHiperTexto($cedula);
             if ($resultadoTexto) {
            $this->render('ficha', array('resultado' => $resultado, 'resultadoTexto' => $resultadoTexto));
        } else {
            $this->render("//msgBox", array('class' => 'errorDialogBox', 'message' => 'Número de Cédula no Existe en el Sistema'));
        }
        }
       
        $this->render('busqueda_avanzada', array());
        
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Document('search');
        $model->unsetAttributes();  // clear any default values
        if ($this->hasQuery('Document')) {
            $model->attributes = $this->getQuery('Document');
        }
        $dataProvider = $model->search();
        $this->render('admin', array(
            'model' => $model,
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionConsulta($id) {
        $idDecoded = $this->getIdDecoded($id);
        $model = $this->loadModel($idDecoded);
        $this->render('view', array(
            'model' => $model,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionRegistro() {
        $model = new Document;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if ($this->hasPost('Document')) {
            $model->attributes = $this->getPost('Document');
            if ($model->save()) {
                $this->redirect(array('consulta', 'id' => $model->id));
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionEdicion($id) {
        $idDecoded = $this->getIdDecoded($id);
        $model = $this->loadModel($idDecoded);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if ($this->hasPost('Document')) {
            $model->attributes = $this->getPost('Document');
            if ($model->save()) {
                if (Yii::app()->request->isAjaxRequest) {
                    $this->renderPartial('//msgBox', array('class' => 'successDialogBox', 'message' => 'La actualización de los Datos se ha efectuado de forma exitosa.'));
                    Yii::app()->end();
                }
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionEliminacion($id) {
        $idDecoded = $this->getIdDecoded($id);
        $model = $this->loadModel($idDecoded);
        // Descomenta este código para habilitar la eliminación física de registros.
        // $model->delete();
        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!$this->hasQuery('ajax')) {
            $this->redirect($this->hasPost('returnUrl') ? $this->getPost('returnUrl') : array('lista'));
        }
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Document the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Document::model()->findByPk($id);
        if ($model === null) {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Document $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if ($this->hasPost('ajax') && $this->getPost('ajax') === 'document-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    /**
     * Retorna los botones o íconos de administración del modelo
     *
     * @param mixed $data
     *
     */
    public function getActionButtons($data) {
        $id_encoded = $data["ubicacion"];
        $id = base64_encode($id_encoded);
        $columna = '<div class="action-buttons">';
        $columna .= CHtml::link("", "", array("class" => "fa icon-zoom-in", "title" => "Ver datos", 'href' => '/document/consulta/id/' . $id)) . '  ';
        $columna .= CHtml::link("", "", array("class" => "fa icon-pencil green", "title" => "Editar datos", 'href' => '/document/edicion/id/' . $id)) . '  ';
        $columna .= CHtml::link("", "", array("class" => "fa icon-trash red", "title" => "Eliminar datos", 'href' => '/document/eliminacion/id/' . $id)) . '  ';
        $columna .= '</div>';
        return $columna;
    }

    /**
     * Obtiene un id Decodificado si un Id es codificado en base64
     *
     * @param mixed $id
     *
     */
    public function getIdDecoded($id) {
        if (is_numeric($id)) {
            return $id;
        } else {
            $idDecodedb64 = base64_decode($id);
            if (is_numeric($idDecodedb64)) {
                return $idDecodedb64;
            }
        }
        return null;
    }

}

web/protected/modules/expediente/views/document/_form.php
<div id="validaciones"></div>
<?php $form=$this->beginWidget('CActiveForm', array(
                                'id'=>'document-form',
                                'enableAjaxValidation'=>false,
                        )); ?>
<?php echo '<input type="hidden" id="zona_id"  name="zona_id"/>'; ?>
                            <div class="col-md-12" id ="">
                                <div class="col-md-5">
                                    <div class="col-md-12"><label for="Plantel_cedula">Cédula<span class="required">*</span></label></div>
                                    <?php echo '<input type="text" data-toggle="tooltip" data-placement="bottom" placeholder="0123456789" title="Ej: 99999999" style="padding:3px 4px" maxlength="10" size="10" id="cedula" class="span-6" name="cedula"/>'; ?>
                                    <?php echo CHtml::button('Busqueda', array('class'=>'btn btn-info btn-xs','submit' => array('document/busqueda'))); ?>

                                </div>
                            </div>


                        <?php $this->endWidget();
?>
<script type="text/javascript">
       $('#cedula').bind('keyup blur', function() {
           keyNum(this, true);
       });
       $('#cedula').bind('blur', function() {
           clearField(this);
       });
     $("#yt0").click(function() {
       var cedula = $.trim($('#cedula').val());
       if (cedula == "") {
           displayDialogBox('validaciones', 'error', 'Datos Faltantes: El Campo Cédula No Puede Ser Vacio.');
           return false;
       }
   });
</script>
</script>               

web/protected/modules/expediente/views/document/admin.php
<?php
/* @var $this DocumentController */
/* @var $model Document */

$this->breadcrumbs = array(
    'Documentos',
);
$this->pageTitle = 'Administración de Documentos';
?>
<div class="widget-box">
    <div class="widget-header">
        <h4>Expedientes</h4>

        <div class="widget-toolbar">
            <a href="#" data-action="collapse">
                <i class="icon-chevron-up"></i>
            </a>
        </div>
    </div>

    <div class="widget-body">
        <div style="display:block;" class="widget-body-inner">
            <div class="widget-main">

                <div class="row space-6"></div>
                    <div id="resultadoOperacion">
                        <div class="infoDialogBox">
                            <p>
                                En Este Módulo Podrá Realizar La Búsqueda.
                            </p>
                        </div>
                    </div>
                
                
                <div>                   
                           

 <?php $this->renderPartial('_form');
                            ?>
                    <br>
                    <br>
                     <br>
                            </div>
                </div>
            </div>
        </div>

web/protected/modules/expediente/views/document/busqueda.php
     <?php $form=$this->beginWidget('CActiveForm', array(
                                'id'=>'document-form',
                                'htmlOptions' => array('data-form-type'=>$formType,), // for inset effect
                                // Please note: When you enable ajax validation, make sure the corresponding
                                // controller action is handling ajax validation correctly.
                                // There is a call to performAjaxValidation() commented in generated controller code.
                                // See class documentation of CActiveForm for details on this.
                                'enableAjaxValidation'=>false,
                        )); ?>

<?php echo '<input type="hidden" id="zona_id"  name="zona_id"/>'; ?>
                            <div class="col-md-12" id ="">
                                <div class="col-md-5">
                                    <div class="col-md-12"><label for="Plantel_cedula">Cédula<span class="required">*</span></label></div>
                                    <?php echo '<input type="text" data-toggle="tooltip" data-placement="bottom" placeholder="0123456789" title="Ej: 99999999"   style="padding:3px 4px" maxlength="10" size="10" class="span-6" name="cedula"/>'; ?>
                                    <?php echo CHtml::button('Busqueda', array('class'=>'btn btn-info btn-xs','submit' => array('document/busqueda'))); ?>

                                </div>
                            </div>

web/protected/modules/expediente/views/document/busqueda_avanzada.php
<?php
/* @var $this DocumentController */
/* @var $model Document */

$this->breadcrumbs = array(
    'Documentos',
);
$this->pageTitle = 'Administración de Documentos';
?>
<div class="widget-box">
    <div class="widget-header">
        <h4>Expedientes</h4>

        <div class="widget-toolbar">
            <a href="#" data-action="collapse">
                <i class="icon-chevron-up"></i>
            </a>
        </div>
    </div>

    <div class="widget-body">
        <div style="display:block;" class="widget-body-inner">
            <div class="widget-main">

                <div class="row space-6"></div>
                    <div id="resultadoOperacion">
                        <div class="infoDialogBox">
                            <p>
                                En Este Módulo Podrá Realizar La Búsqueda Por Cédula, Nombre, Apellido Ó Número De Expediente.
                            </p>
                        </div>
                    </div>
                
                
                <div>        

<?php $form=$this->beginWidget('CActiveForm', array(
                                'id'=>'document-form',
                                //'htmlOptions' => array('data-form-type'=>$formType,), // for inset effect
                                // Please note: When you enable ajax validation, make sure the corresponding
                                // controller action is handling ajax validation correctly.
                                // There is a call to performAjaxValidation() commented in generated controller code.
                                // See class documentation of CActiveForm for details on this.
                                'enableAjaxValidation'=>false,
                        )); ?>

<?php echo '<input type="hidden" id="zona_id"  name="zona_id"/>'; ?>
                            <div class="col-md-12" id ="">
                                <div class="col-md-5">
                                    <div class="col-md-12"><label for="Plantel_cedula">Cédula<span class="required">*</span></label></div>
                                    <?php echo '<input type="text" data-toggle="tooltip" data-placement="bottom" placeholder="0123456789" title="Ej: 99999999"   style="padding:3px 4px" maxlength="10" size="10" class="span-6" name="cedula"/>'; ?>
                                    <?php echo CHtml::button('Busqueda', array('class'=>'btn btn-info btn-xs','submit' => array('document/busqueda'))); ?>

                                </div>
                            </div>
                    
<?php echo '<input type="hidden" id="zona_id"  name="zona_id"/>'; ?>
                            <div class="col-md-12" id ="">
                                <div class="col-md-5">
                                    <div class="col-md-12"><label for="Plantel_cedula">Número De Expediente<span class="required">*</span></label></div>
                                    <?php echo '<input type="text" data-toggle="tooltip" data-placement="bottom" placeholder="0123456789" title="Ej: 99999999"   style="padding:3px 4px" maxlength="10" size="10" class="span-6" name="cedula"/>'; ?>
                                    <?php echo CHtml::button('Busqueda', array('class'=>'btn btn-info btn-xs','submit' => array('document/busqueda'))); ?>

                                </div>
                            </div>
                    
<?php echo '<input type="hidden" id="zona_id"  name="zona_id"/>'; ?>
                            <div class="col-md-12" id ="">
                                <div class="col-md-5">
                                    <div class="col-md-12"><label for="Plantel_cedula">Nombres y Apellidos<span class="required">*</span></label></div>
                                    <?php echo '<input type="text" data-toggle="tooltip" data-placement="bottom" placeholder="ABCDEFHIJKL" title="Ej: ABCDEFHIJKL"   style="padding:3px 4px" maxlength="10" size="10" class="span-6" name="cedula"/>'; ?>
                                    <?php echo CHtml::button('Busqueda', array('class'=>'btn btn-info btn-xs','submit' => array('document/busqueda'))); ?>

                                </div>
                            </div>
<?php
 $this->endWidget();?>

                                       <br>
                    <br>
                     <br>
                            </div>
                </div>
            </div>
        </div>

web/protected/modules/expediente/views/document/create.php
<?php
/* @var $this DocumentController */
/* @var $model Document */

$this->pageTitle = 'Registro De Documentos';

      $this->breadcrumbs=array(
	'Documents'=>array('lista'),
	'Registro',
);
?>

<?php $this->renderPartial('_form', array('model'=>$model, 'formType'=>'registro')); ?>

web/protected/modules/expediente/views/document/index.php
<?php

/* @var $this DocumentController */
/* @var $model Document */

$this->breadcrumbs=array(
	'Documents'=>array('lista'),
	'Administración',
);
$this->pageTitle = 'Administración De Documentos';

?>
<div class="widget-box">
    <div class="widget-header">
        <h4>Lista De Documentos</h4>

        <div class="widget-toolbar">
            <a href="#" data-action="collapse">
                <i class="icon-chevron-up"></i>
            </a>
        </div>
    </div>

    <div class="widget-body">
        <div style="display:block;" class="widget-body-inner">
            <div class="widget-main">

                <div class="row space-6"></div>
                <div>
                    <div id="resultadoOperacion">
                        <div class="infoDialogBox">
                            <p>
                                En Este Módulo Podrá Registrar Y/O/U Actualizar Los Datos De Los Documentos.
                            </p>
                        </div>
                    </div>

                    <div class="pull-right" style="padding-left:10px;">
                        <a href="<?php echo $this->createUrl("/document/registro"); ?>" type="submit" id='newRegister' data-last="Finish" class="btn btn-success btn-next btn-sm">
                            <i class="fa fa-plus icon-on-right"></i>
                            Registrar Nuevo Documentos                        </a>
                    </div>


                    <div class="row space-20"></div>

                </div>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'document-grid',
	'dataProvider'=>$dataProvider,
        'filter'=>$model,
        'itemsCssClass' => 'table table-striped table-bordered table-hover',
        'summaryText' => 'Mostrando {start}-{end} de {count}',
        'pager' => array(
            'header' => '',
            'htmlOptions' => array('class' => 'pagination'),
            'firstPageLabel' => '<span title="Primera página">&#9668;&#9668;</span>',
            'prevPageLabel' => '<span title="Página Anterior">&#9668;</span>',
            'nextPageLabel' => '<span title="Página Siguiente">&#9658;</span>',
            'lastPageLabel' => '<span title="Última página">&#9658;&#9658;</span>',
        ),
        'afterAjaxUpdate' => "
                function(){

                }",
	'columns'=>array(
        array(
            'header' => '<center>acceso</center>',
            'name' => 'acceso',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[acceso]', $model->acceso, array('title' => '',)),
        ),
        array(
            'header' => '<center>ext_acceso</center>',
            'name' => 'ext_acceso',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[ext_acceso]', $model->ext_acceso, array('title' => '',)),
        ),
        array(
            'header' => '<center>jerarquia</center>',
            'name' => 'jerarquia',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[jerarquia]', $model->jerarquia, array('title' => '',)),
        ),
        array(
            'header' => '<center>ubicacion</center>',
            'name' => 'ubicacion',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[ubicacion]', $model->ubicacion, array('title' => '',)),
        ),
        array(
            'header' => '<center>tipo_liter</center>',
            'name' => 'tipo_liter',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[tipo_liter]', $model->tipo_liter, array('title' => '',)),
        ),
        array(
            'header' => '<center>nivel_bibl</center>',
            'name' => 'nivel_bibl',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[nivel_bibl]', $model->nivel_bibl, array('title' => '',)),
        ),
		/*
        array(
            'header' => '<center>nivel_reg</center>',
            'name' => 'nivel_reg',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[nivel_reg]', $model->nivel_reg, array('title' => '',)),
        ),
        array(
            'header' => '<center>tipo_ref_analitica</center>',
            'name' => 'tipo_ref_analitica',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[tipo_ref_analitica]', $model->tipo_ref_analitica, array('title' => '',)),
        ),
        array(
            'header' => '<center>paginas</center>',
            'name' => 'paginas',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[paginas]', $model->paginas, array('title' => '',)),
        ),
        array(
            'header' => '<center>volumen</center>',
            'name' => 'volumen',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[volumen]', $model->volumen, array('title' => '',)),
        ),
        array(
            'header' => '<center>volumen_final</center>',
            'name' => 'volumen_final',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[volumen_final]', $model->volumen_final, array('title' => '',)),
        ),
        array(
            'header' => '<center>numero</center>',
            'name' => 'numero',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[numero]', $model->numero, array('title' => '',)),
        ),
        array(
            'header' => '<center>numero_final</center>',
            'name' => 'numero_final',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[numero_final]', $model->numero_final, array('title' => '',)),
        ),
        array(
            'header' => '<center>numeracion</center>',
            'name' => 'numeracion',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[numeracion]', $model->numeracion, array('title' => '',)),
        ),
        array(
            'header' => '<center>enum_nivel_ini_3</center>',
            'name' => 'enum_nivel_ini_3',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[enum_nivel_ini_3]', $model->enum_nivel_ini_3, array('title' => '',)),
        ),
        array(
            'header' => '<center>enum_nivel_ini_4</center>',
            'name' => 'enum_nivel_ini_4',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[enum_nivel_ini_4]', $model->enum_nivel_ini_4, array('title' => '',)),
        ),
        array(
            'header' => '<center>enum_nivel_fin_3</center>',
            'name' => 'enum_nivel_fin_3',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[enum_nivel_fin_3]', $model->enum_nivel_fin_3, array('title' => '',)),
        ),
        array(
            'header' => '<center>enum_nivel_fin_4</center>',
            'name' => 'enum_nivel_fin_4',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[enum_nivel_fin_4]', $model->enum_nivel_fin_4, array('title' => '',)),
        ),
        array(
            'header' => '<center>cod_editor</center>',
            'name' => 'cod_editor',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[cod_editor]', $model->cod_editor, array('title' => '',)),
        ),
        array(
            'header' => '<center>cod_editor_inst</center>',
            'name' => 'cod_editor_inst',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[cod_editor_inst]', $model->cod_editor_inst, array('title' => '',)),
        ),
        array(
            'header' => '<center>edicion</center>',
            'name' => 'edicion',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[edicion]', $model->edicion, array('title' => '',)),
        ),
        array(
            'header' => '<center>fecha_iso</center>',
            'name' => 'fecha_iso',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[fecha_iso]', $model->fecha_iso, array('title' => '',)),
        ),
        array(
            'header' => '<center>fecha_iso_final</center>',
            'name' => 'fecha_iso_final',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[fecha_iso_final]', $model->fecha_iso_final, array('title' => '',)),
        ),
        array(
            'header' => '<center>fecha_pub</center>',
            'name' => 'fecha_pub',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[fecha_pub]', $model->fecha_pub, array('title' => '',)),
        ),
        array(
            'header' => '<center>isbn</center>',
            'name' => 'isbn',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[isbn]', $model->isbn, array('title' => '',)),
        ),
        array(
            'header' => '<center>indice_suplemento</center>',
            'name' => 'indice_suplemento',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[indice_suplemento]', $model->indice_suplemento, array('title' => '',)),
        ),
        array(
            'header' => '<center>cod_conf</center>',
            'name' => 'cod_conf',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[cod_conf]', $model->cod_conf, array('title' => '',)),
        ),
        array(
            'header' => '<center>cod_proy</center>',
            'name' => 'cod_proy',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[cod_proy]', $model->cod_proy, array('title' => '',)),
        ),
        array(
            'header' => '<center>disemina</center>',
            'name' => 'disemina',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[disemina]', $model->disemina, array('title' => '',)),
        ),
        array(
            'header' => '<center>url</center>',
            'name' => 'url',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[url]', $model->url, array('title' => '',)),
        ),
        array(
            'header' => '<center>n_disk_cin</center>',
            'name' => 'n_disk_cin',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[n_disk_cin]', $model->n_disk_cin, array('title' => '',)),
        ),
        array(
            'header' => '<center>sala</center>',
            'name' => 'sala',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[sala]', $model->sala, array('title' => '',)),
        ),
        array(
            'header' => '<center>impresion</center>',
            'name' => 'impresion',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[impresion]', $model->impresion, array('title' => '',)),
        ),
        array(
            'header' => '<center>orden</center>',
            'name' => 'orden',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[orden]', $model->orden, array('title' => '',)),
        ),
        array(
            'header' => '<center>cerrado</center>',
            'name' => 'cerrado',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[cerrado]', $model->cerrado, array('title' => '',)),
        ),
        array(
            'header' => '<center>hora_iso_inicio</center>',
            'name' => 'hora_iso_inicio',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[hora_iso_inicio]', $model->hora_iso_inicio, array('title' => '',)),
        ),
        array(
            'header' => '<center>hora_iso_final</center>',
            'name' => 'hora_iso_final',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[hora_iso_final]', $model->hora_iso_final, array('title' => '',)),
        ),
        array(
            'header' => '<center>id</center>',
            'name' => 'id',
            'htmlOptions' => array(),
            //'filter' => CHtml::textField('Document[id]', $model->id, array('title' => '',)),
        ),
		*/
		array(
                    'type' => 'raw',
                    'header' => '<center>Acción</center>',
                    'value' => array($this, 'getActionButtons'),
                    'htmlOptions' => array('nowrap'=>'nowrap'),
                ),
	),
)); ?>
            </div>
        </div>
    </div>
</div>

web/protected/modules/expediente/views/document/update.php
<?php
/* @var $this DocumentController */
/* @var $model Document */

$this->pageTitle = 'Actualización De Datos De Documentos';

      $this->breadcrumbs=array(
	'Documents'=>array('lista'),
	'Actualización',
);
?>

<?php $this->renderPartial('_form', array('model'=>$model, 'formType'=>'edicion')); ?>